# Use Fedora as the base image
FROM fedora

# Update and install required system dependencies
RUN dnf -y update && \
    dnf -y install python3 ipython3 python3-pip g++ gcc python3-PyQt5 python3-matplotlib python3-devel \
    python3-netifaces python3-h5py python3-scipy python3-numcodecs python3-pandas libpng15 git \
    python3-redis python3-scikit-image python3-zmq python3-kafka python3-pymongo python3-pycurl

# Install UV from Astral
RUN pip3 install uv

# Use UV to accelerate Python package installations
RUN uv pip install --system\
    caproto[standard] jupyter httpie fastapi uvicorn[standard] bluesky-tiled-plugins\
    python-jose[cryptography] passlib[bcrypt] pykafka confluent_kafka nslsii tiled[all] scikit-learn scipy

# Create a configuration directory and add configuration files
RUN mkdir -p /etc/bluesky
ADD kafka.yml /etc/bluesky/kafka.yml

# Build font cache for matplotlib
RUN python3 -c "import matplotlib.font_manager"

# Use UV for Bluesky and related dependencies
RUN uv pip install --system git+https://github.com/bluesky/bluesky-adaptive.git@main#egg=bluesky-adaptive
RUN uv pip install --system git+https://github.com/bluesky/bluesky-queueserver.git@main#egg=bluesky-queueserver
RUN uv pip install --system git+https://github.com/bluesky/bluesky-httpserver.git@master#egg=bluesky-httpserver
RUN uv pip install --system git+https://github.com/bluesky/bluesky-widgets.git@master#egg=bluesky-widgets
RUN uv pip install --system git+https://github.com/pcdshub/happi.git@master#egg=happi
RUN uv pip install --system git+https://github.com/bluesky/databroker.git@v2.0.0b58#egg=databroker


# Remove unnecessary packages (if needed)
RUN pip3 uninstall --yes pyepics
RUN uv pip install --system json-rpc dash dash-daq requests
